// Testing function for libdbquery autogenerated code
#include <string>
#include <iostream>
#include "neuronschema.hpp"



using namespace std;
using namespace neuronSchema;

int main (int argc, char** argv)
{
	cout << "Testing function for libdbquery autogenerated code" << endl;
	// Load the NeuronSchema object
	neuronSchema::neuronSchema sc("host=localhost dbname=neurondb user=neuron  password=neuron");
	//Perform Connection
	sc.connectDB();
	//Query the database
	ptbody bodypt = sc.gtbody(1);
	//Print out the data
	cout << "Body Name: " << bodypt->name << endl;
}
