// Testing function for libdbquery autogenerated code
#include <string>
#include <iostream>
#include "neuronschema.hpp"



using namespace std;
using namespace dbquery;
using namespace neuronSchema;

int main (int argc, char** argv)
{
	cout << "Testing function for libdbquery autogenerated code" << endl;
	//1. Create connection object
	DBConnection dbc("host=localhost dbname=neurondb user=neuron  password=neuron");
	//2. Connect to the database
	dbc.connectDB();
	//3. Build a transaction object
	dbt = DBTransaction(dbc);
	//4. Create schema class
	neuronSchema sc(dbc, dbt);
	//5. Initialise schema class
	sc.initialise();
	//6. Build our objects
	//Query the database
	//Print out the data
	cout << "Body Name: " << bodypt->name << endl;
	//7. Modify data
	//8. New data
	// Perform an Insert
	ptbody bodyptNew = sc.inserttbody("Earthshine");
	//9. Commit Changes
	dbt.saveTransaction();
	// Get the ID
	cout << "New Body Name: " << bodyptNew->getName() << endl;
	// Print out the data
	cout << "New Body ID: " << bodyptNew->getId() << endl;
	//Fetch a new Identifier
	ptbody bodyptNew2 = sc.gtbody(bodyptNew->getId());
	// Make sure we got the right name
	cout << "New Body ID: " << bodyptNew2->getName() << endl;
}
