// Testing function for libdbquery autogenerated code
#include <string>
#include <iostream>

#include "dbconnection.hpp"
#include "dbtransaction.hpp"
#include "neuronschema.hpp"



using namespace std;
using namespace dbquery;
using namespace neuronSchema;

int main (int argc, char** argv)
{
	cout << "Testing function for libdbquery autogenerated code" << endl;
	//1. Create connection object
	DBConnection dbc("host=localhost dbname=neurondb user=neuron  password=neuron");
	//2. Connect to the database
	dbc.connectDB();
	//3. Build a transaction object
	DBTransaction dbt(&dbc);
	//4. Create schema class
	neuronSchema::neuronSchema sc(dbc, &dbt);
	//5. Initialise schema class
	sc.initialise();
	//6. Build our objects
	//Query the database
	ptbody bodypt = sc.gtbody(1);
	// Print out the data
	cout << "New Body ID: " << bodypt->getId() << endl;
	cout << "Body Name: " << bodypt->name << endl;
	//7. Modify data
	//8. New data
	// Perform an Insert
	ptbody bodyptNew = sc.inserttbody("Earthshine");
	//9. Commit Changes
	dbt.saveTransaction();
}
